# Generated by Django 5.1.2 on 2025-03-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='unique_cuenta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cuenta',
        ),
    ]
