# Generated by Django 5.1.2 on 2025-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_usuario_unique_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'MESERO'), (2, 'COCINA'), (3, 'GESTOR')]),
        ),
    ]
