# Generated by Django 5.1.6 on 2025-03-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='idUsuarioRegistro',
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='nombre_producto',
            field=models.CharField(default='SIN NOMBRE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_registro',
            field=models.CharField(default='SIN USUARIO', max_length=150),
            preserve_default=False,
        ),
    ]
