# Generated by Django 5.1.6 on 2025-03-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_detalle_pedido_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
    ]
